language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t viniciusilveira/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true viniciusilveira/docker-react npm run test

# deploy settings
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "docker-react-env"
#   bucket_name: "elasticbeanstalk-us-west-2-<key>"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
